strategy:
  name: semantic
  common:
    chunk_size: 600
    chunk_overlap: 100
  semantic:
    model_name: sentence-transformers/all-MiniLM-L6-v2
    embedding_model: text-embedding-v3
    min_similarity: 0.65
